// apps/nuxt/app/components/Header.vue
<script setup lang="ts">
import {} from "lucide-vue-next"
import { Button } from "@/components/ui/button.vue"

const isOpen = ref(false)

const toggleMenu = () => {
    isOpen.value = !isOpen.value
}

const closeMenu = () => {
    isOpen.value = false
}
</script>

<template>
    <header class="fixed top-0 w-full z-50 border-b border-muted bg-black/80 backdrop-blur-md">
        <nav class="w-11/12 max-w-5xl mx-auto py-4 flex items-center justify-between">
            <a class="text-xl font-semibold" href="/">Aura Auth</a>
            <ul
                class="hidden md:flex items-center justify-center gap-8 absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2"
            >
                <a class="text-sm text-white/60 transition-colors hover:text-white" href="/">Documentation</a>
                <a class="text-sm text-white/60 transition-colors hover:text-white" href="/">Repository</a>
                <a class="text-sm text-white/60 transition-colors hover:text-white" href="/">Discord</a>
            </ul>
            <Button variant="outline"> nose </Button>
        </nav>
        <div className="md:hidden bg-black/95 backdrop-blur-md border-t border-gray-800/50 animate-[slideDown_0.3s_ease-out]">
            <div className="px-6 py-4 flex flex-col gap-4">
                <NuxtLink to="/signIn" className="text-sm text-white/60 hover:text-white transition-colors py-2">
                    Getting started
                </NuxtLink>
                <a
                    href="https://github.com/aura-stack-ts/auth"
                    className="text-sm text-white/60 hover:text-white transition-colors py-2"
                    target="_blank"
                >
                    Repository
                </a>
                <a
                    href="https://discord.com/invite/anXExMR5"
                    className="text-sm text-white/60 hover:text-white transition-colors py-2"
                    target="_blank"
                >
                    Discord
                </a>
                <div className="flex flex-col gap-2 pt-4 border-t border-gray-800/50"></div>
            </div>
        </div>
    </header>
</template>

// apps/tanstack-start/src/components/header.tsx
import { useState } from "react"
import { Menu, X } from "lucide-react"
import { useSession } from "@/contexts/auth"
import { Link } from "@tanstack/react-router"
import { Button } from "@/components/ui/button"

export const Header = () => {
    const { isAuthenticated, isLoading, signOut } = useSession()
    const [mobileMenuOpen, setMobileMenuOpen] = useState(false)

    const handleSignOut = async () => {
        await signOut()
    }

    return (
        <header className="fixed top-0 w-full z-50 border-b border-muted bg-black/80 backdrop-blur-md">
            <nav className="w-11/12 max-w-5xl mx-auto py-4">
                <div className="flex items-center justify-between">
                    <Link to="/" className="text-xl font-semibold text-white">
                        Aura Auth
                    </Link>
                    <div className="hidden md:flex items-center justify-center gap-8 absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2">
                        <a
                            href="https://aura-stack-auth.vercel.app/docs"
                            className="text-sm text-white/60 hover:text-white transition-colors"
                            target="_blank"
                        >
                            Documentation
                        </a>
                        <a
                            href="https://github.com/aura-stack-ts/auth"
                            className="text-sm text-white/60 hover:text-white transition-colors"
                            target="_blank"
                        >
                            Repository
                        </a>
                        <a
                            href="https://discord.com/invite/anXExMR5"
                            className="text-sm text-white/60 hover:text-white transition-colors"
                            target="_blank"
                        >
                            Discord
                        </a>
                    </div>
                    {!isAuthenticated && (
                        <Button className="hidden md:flex" variant="outline" size="sm" asChild>
                            <Link to="/signIn">Sign In</Link>
                        </Button>
                    )}
                    {isAuthenticated && (
                        <div className="hidden md:flex items-center gap-x-2">
                            <Button variant="outline" size="sm" onClick={handleSignOut}>
                                Sign Out
                            </Button>
                            <Button size="sm" asChild>
                                <Link to="/users/profile">Profile</Link>
                            </Button>
                        </div>
                    )}
                    <button
                        type="button"
                        className="md:hidden text-white"
                        onClick={() => setMobileMenuOpen(!mobileMenuOpen)}
                        aria-label="Toggle menu"
                    >
                        {mobileMenuOpen ? <X size={24} /> : <Menu size={24} />}
                    </button>
                </div>
            </nav>
            {mobileMenuOpen && (
                <div className="md:hidden bg-black/95 backdrop-blur-md border-t border-gray-800/50 animate-[slideDown_0.3s_ease-out]">
                    <div className="px-6 py-4 flex flex-col gap-4">
                        <Link
                            to="/signIn"
                            className="text-sm text-white/60 hover:text-white transition-colors py-2"
                            onClick={() => setMobileMenuOpen(false)}
                        >
                            Getting started
                        </Link>
                        <a
                            href="https://github.com/aura-stack-ts/auth"
                            className="text-sm text-white/60 hover:text-white transition-colors py-2"
                            target="_blank"
                            onClick={() => setMobileMenuOpen(false)}
                        >
                            Repository
                        </a>
                        <a
                            href="https://discord.com/invite/anXExMR5"
                            className="text-sm text-white/60 hover:text-white transition-colors py-2"
                            target="_blank"
                            onClick={() => setMobileMenuOpen(false)}
                        >
                            Discord
                        </a>
                        <div className="flex flex-col gap-2 pt-4 border-t border-gray-800/50">
                            {!isLoading && !isAuthenticated && (
                                <Button type="button" variant="ghost" size="sm" asChild>
                                    <Link to="/signIn">Sign in</Link>
                                </Button>
                            )}
                            {isAuthenticated && (
                                <div className="flex flex-col items-center gap-y-3 md:hidden">
                                    <Button className="w-full" variant="outline" size="sm" onClick={handleSignOut}>
                                        Sign Out
                                    </Button>
                                    <Button className="w-full" size="sm" asChild>
                                        <Link to="/users/profile">Profile</Link>
                                    </Button>
                                </div>
                            )}
                        </div>
                    </div>
                </div>
            )}
        </header>
    )
}

Header.displayName = "Header"
