// apps/tanstack-start/src/components/footer.tsx
import { GithubIcon } from "lucide-react"

export const Footer = () => {
    const year = new Date().getFullYear()

    const community = [
        {
            title: "Discord Support",
            href: "https://discord.com/invite/anXExMR5",
        },
    ]

    const resources = [
        {
            title: "Documentation",
            href: "https://aura-stack-auth.vercel.app/docs/introduction",
        },
        {
            title: "GitHub Repository",
            href: "https://github.com/aura-stack-ts/auth",
        },
        {
            title: "NPM Registry",
            href: "https://npmjs.com/package/@aura-stack/auth",
        },
    ]

    const socialLinks = [
        {
            icon: <GithubIcon className="size-4" />,
            link: "https://github.com/aura-stack-ts/auth",
        },
    ]

    return (
        <footer className="relative border-t bg-black">
            <div className="w-11/12 mx-auto max-w-6xl border-x border-muted">
                <div className="py-10 px-6 max-w-5xl grid grid-cols-6 gap-6">
                    <div className="col-span-6 flex flex-col gap-5 md:col-span-4">
                        <a href="https://aura-stack-auth.vercel.app/" className="w-max opacity-25">
                            Aura Auth
                        </a>
                        <p className="max-w-sm text-muted-foreground font-mono text-sm text-balance">
                            Built for speed, security, and developer experience. The complete authentication library for
                            TypeScript applications.
                        </p>
                        <div className="flex gap-2">
                            {socialLinks.map((item, i) => (
                                <li key={i}>
                                    <a
                                        className="p-1.5 border rounded-md hover:bg-accent"
                                        target="_blank"
                                        href={item.link}
                                        rel="noopener noreferrer"
                                    >
                                        {item.icon}
                                    </a>
                                </li>
                            ))}
                        </div>
                    </div>
                    <div className="col-span-3 w-full base:col-span-1">
                        <span className="mb-1 text-sm">Resources</span>
                        <ul className="flex flex-col gap-1">
                            {resources.map(({ href, title }, i) => (
                                <li key={i}>
                                    <a
                                        className="w-max py-1 text-xs text-muted-foreground duration-200 hover:underline"
                                        href={href}
                                        target="_blank"
                                        rel="noopener noreferrer"
                                    >
                                        {title}
                                    </a>
                                </li>
                            ))}
                        </ul>
                    </div>
                    <div className="col-span-3 w-full base:col-span-1">
                        <span className="mb-1 text-sm">Community</span>
                        <ul className="flex flex-col gap-1">
                            {community.map(({ href, title }, i) => (
                                <li key={i}>
                                    <a
                                        className="w-max py-1 text-xs text-muted-foreground duration-200 hover:underline"
                                        href={href}
                                        target="_blank"
                                        rel="noopener noreferrer"
                                    >
                                        {title}
                                    </a>
                                </li>
                            ))}
                        </ul>
                    </div>
                </div>
                <div className="w-full h-px absolute inset-x-0 bg-border" />
                <div className="max-w-6xl py-4 flex flex-col justify-between gap-2">
                    <p className="text-sm text-muted-foreground text-center font-thin">
                        ©{" "}
                        <a href="https://github.com/aura-stack-ts" target="_blank" rel="noopener noreferrer">
                            Aura Stack Labs
                        </a>
                        . All rights reserved {year}
                    </p>
                </div>
            </div>
        </footer>
    )
}

Footer.displayName = "Footer"

// apps/nuxt/app/components/footer.vue
<script setup lang="ts">
import { GithubIcon } from "lucide-vue-next"

const community = [
    {
        title: "Discord Support",
        href: "https://discord.com/invite/anXExMR5",
    },
]

const resources = [
    {
        title: "Documentation",
        href: "https://aura-stack-auth.vercel.app/docs/introduction",
    },
    {
        title: "GitHub Repository",
        href: "https://github.com/aura-stack-ts/auth",
    },
    {
        title: "NPM Registry",
        href: "https://npmjs.com/package/@aura-stack/auth",
    },
]

const socialLinks = [
    {
        icon: GithubIcon,
        href: "https://github.com/aura-stack-ts/auth",
    },
]
</script>

<template>
    <footer class="relative border-t bg-black">
        <div class="w-11/12 mx-auto max-w-6xl border-x border-muted">
            <div class="max-w-5xl py-10 px-6 grid grid-cols-6 gap-6">
                <div class="col-span-6 flex flex-col gap-5 md:col-span-4">
                    <a href="https://aura-stack-auth.vercel.app/" class="w-max opacity-25">Aura Auth</a>
                    <p class="max-w-sm text-muted-foreground font-mono text-sm text-balance">
                        Built for speed, security, and developer experience. The complete authentication library for TypeScript
                        applications.
                    </p>
                    <div class="flex gap-2">
                        <a
                            v-for="item in socialLinks"
                            :key="item.href"
                            :href="item.href"
                            target="_blank"
                            rel="noopener noreferrer"
                            class="p-1.5 border rounded-md hover:bg-accent"
                        >
                            <component :is="item.icon" class="h-4 w-4" />
                        </a>
                    </div>
                </div>
                <div class="col-span-3 w-full base:col-span-1">
                    <span class="mb-1 text-sm">Resources</span>
                    <ul class="flex flex-col gap-1">
                        <li v-for="item in resources" :key="item.href">
                            <a
                                :href="item.href"
                                target="_blank"
                                rel="noopener noreferrer"
                                class="w-max py-1 text-xs text-muted-foreground duration-200 hover:underline"
                            >
                                {{ item.title }}
                            </a>
                        </li>
                    </ul>
                </div>
                <div class="col-span-3 w-full base:col-span-1">
                    <span class="mb-1 text-sm">Community</span>
                    <ul class="flex flex-col gap-1">
                        <li v-for="item in community" :key="item.href">
                            <a
                                :href="item.href"
                                target="_blank"
                                rel="noopener noreferrer"
                                class="w-max py-1 text-xs text-muted-foreground duration-200 hover:underline"
                            >
                                {{ item.title }}
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="w-full h-px absolute inset-x-0 bg-border" />
            <div class="max-w-6xl py-4 flex flex-col justify-between gap-2">
                <p class="text-sm text-muted-foreground text-center font-thin">
                    © <a href="https://github.com/aura-stack-ts">Aura Stack Labs</a>. All rights reserved
                    {{ new Date().getFullYear() }}
                </p>
            </div>
        </div>
    </footer>
</template>
